# Generated by Django 4.1.4 on 2023-01-05 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import ue_app.models.audio_model
import ue_app.models.video_model
import ue_app.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the title of your post', max_length=500, null=True)),
                ('slug', models.SlugField(max_length=500, null=True)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Publish')], default='Draft', max_length=100, null=True)),
                ('display', models.CharField(choices=[('pr', 'Private'), ('pu', 'Public')], default='Public', max_length=100)),
                ('views', models.PositiveIntegerField(default=0)),
                ('verify', models.BooleanField(default=False)),
                ('like', models.BooleanField(default=False)),
                ('feature_image', models.ImageField(default='article_image', null=True, upload_to='article_images')),
                ('body', models.TextField(null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_uploaded', 'author'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the title of your post', max_length=500, null=True)),
                ('slug', models.SlugField(max_length=500, null=True)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Publish')], default='Draft', max_length=100, null=True)),
                ('display', models.CharField(choices=[('pr', 'Private'), ('pu', 'Public')], default='Public', max_length=100)),
                ('views', models.PositiveIntegerField(default=0)),
                ('verify', models.BooleanField(default=False)),
                ('like', models.BooleanField(default=False)),
                ('feature_image', models.ImageField(blank=True, default='audio_image', null=True, upload_to='audio_images')),
                ('audio_description', models.CharField(blank=True, help_text='Write a short description of your audio', max_length=500, null=True)),
                ('audio_upload', models.FileField(upload_to=ue_app.models.audio_model.user_directory_path, validators=[ue_app.validators.validate_is_audio])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_uploaded', 'author'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Select or Enter your Post category e.g. Travel', max_length=100)),
                ('slug', models.SlugField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(blank=True, help_text='Enter your middle name', max_length=200, null=True)),
                ('phone_number', models.CharField(help_text='Enter your State or Phone Number', max_length=12, null=True)),
                ('address', models.CharField(blank=True, help_text='Enter your House address', max_length=500, null=True)),
                ('city', models.CharField(blank=True, help_text='Enter your City (e.g. Lagos)', max_length=100, null=True)),
                ('region', models.CharField(blank=True, help_text='Enter your State or Region (e.g. Rivers)', max_length=100, null=True)),
                ('country', models.CharField(blank=True, help_text='Enter your Country (e.g. Nigeria)', max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, default='avatar.png', null=True, upload_to='profile_picture')),
                ('bio', models.TextField(blank=True, null=True)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the title of your post', max_length=500, null=True)),
                ('slug', models.SlugField(max_length=500, null=True)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Publish')], default='Draft', max_length=100, null=True)),
                ('display', models.CharField(choices=[('pr', 'Private'), ('pu', 'Public')], default='Public', max_length=100)),
                ('views', models.PositiveIntegerField(default=0)),
                ('verify', models.BooleanField(default=False)),
                ('like', models.BooleanField(default=False)),
                ('video_description', models.CharField(blank=True, help_text='Write a short description of your video', max_length=500, null=True)),
                ('video_upload', models.FileField(upload_to=ue_app.models.video_model.user_directory_path, validators=[ue_app.validators.validate_is_video])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ue_app.category')),
            ],
            options={
                'ordering': ['-date_uploaded', 'author'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(help_text='Enter your comment')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('approved', models.BooleanField(default=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ue_app.channel')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ue_app.videocomment')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ue_app.video')),
            ],
            options={
                'verbose_name': 'Video Comment',
            },
        ),
        migrations.CreateModel(
            name='AudioComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(help_text='Enter your comment')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('approved', models.BooleanField(default=True)),
                ('audio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ue_app.audio')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ue_app.channel')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ue_app.audiocomment')),
            ],
            options={
                'verbose_name': 'Audio Comment',
            },
        ),
        migrations.AddField(
            model_name='audio',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ue_app.category'),
        ),
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(help_text='Enter your comment')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('approved', models.BooleanField(default=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ue_app.article')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ue_app.channel')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ue_app.articlecomment')),
            ],
            options={
                'verbose_name': 'Article Comment',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ue_app.category'),
        ),
    ]
