# Generated by Django 4.1.4 on 2023-01-13 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ue_app', '0004_category_image_channel_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='count_words',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='article',
            name='read_time',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ue_app.channel'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ue_app.channel'),
        ),
        migrations.AlterField(
            model_name='video',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ue_app.channel'),
        ),
    ]
