# Generated by Django 4.1.4 on 2023-01-17 14:01

from django.conf import settings
from django.db import migrations, models
import ue_app.models.audio_model
import ue_app.models.video_model


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ue_app', '0008_alter_article_feature_image_alter_audio_audio_upload_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='like',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='like',
        ),
        migrations.RemoveField(
            model_name='video',
            name='like',
        ),
        migrations.AddField(
            model_name='article',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='audio',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='video',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='feature_image',
            field=models.ImageField(default='article_image', null=True, upload_to='article_images'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='audio_upload',
            field=models.FileField(null=True, upload_to=ue_app.models.audio_model.user_directory_path),
        ),
        migrations.AlterField(
            model_name='audio',
            name='feature_image',
            field=models.ImageField(blank=True, default='audio_image', null=True, upload_to='audio_images'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_upload',
            field=models.FileField(null=True, upload_to=ue_app.models.video_model.user_directory_path),
        ),
    ]
