# Generated by Django 4.1.4 on 2023-02-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ue_app', '0011_rename_bio_channel_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='slug',
            field=models.SlugField(max_length=500, null=True),
        ),
    ]
