# Generated by Django 4.1.4 on 2023-02-21 11:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ue_app', '0012_channel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='channel_logo',
            field=models.ImageField(blank=True, default='channel.png', null=True, upload_to='channel_logo'),
        ),
        migrations.AddField(
            model_name='channel',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='follow',
            field=models.ManyToManyField(null=True, related_name='follow', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
