# Generated by Django 4.1.4 on 2023-03-03 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ue_app', '0014_remove_profile_middle_name_profile_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecomment',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='audiocomment',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='videocomment',
            name='channel',
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='audiocomment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='videocomment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='comment',
            field=models.TextField(help_text='Enter your comment', null=True),
        ),
        migrations.AlterField(
            model_name='audiocomment',
            name='comment',
            field=models.TextField(help_text='Enter your comment', null=True),
        ),
        migrations.AlterField(
            model_name='videocomment',
            name='comment',
            field=models.TextField(help_text='Enter your comment', null=True),
        ),
    ]
